'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Res1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Route_Converter.Res1", GetType(Res1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Public Shared ReadOnly Property ex() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("ex", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;!DOCTYPE root&gt;
        '''&lt;route xmlns=&quot;http://www.sevencs.com/eglobe/route&quot; name=&quot;?????&quot; version=&quot;3&quot;&gt;
        '''&lt;metadata&gt;
        '''&lt;author&gt;SevenCs eGlobe 1.1.1.17&lt;/author&gt;
        '''&lt;timestamp&gt;2017-11-16T08:19:09&lt;/timestamp&gt;
        '''&lt;/metadata&gt;
        '''&lt;defaults&gt;
        '''&lt;xte&gt;
        '''&lt;both-sided&gt;100&lt;/both-sided&gt;
        '''&lt;/xte&gt;
        '''&lt;turningRadius&gt;200&lt;/turningRadius&gt;
        '''&lt;plannedSpeed&gt;0&lt;/plannedSpeed&gt;
        '''&lt;/defaults&gt;
        '''&lt;routecheck&gt;
        '''&lt;routeLastCheck&gt;2017-11-16T08:12:29&lt;/routeLastCheck&gt;
        '''&lt;routeCheckProvider&gt;eGlobeMaster&lt;/routeCheckProvider&gt;
        '''&lt;routeCheckDraft&gt;9&lt;/ro [rest of string was truncated]&quot;;.
        '''</summary>
        Public Shared ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;waypoint name=&quot;@@@@@&quot;&gt;
        '''&lt;position latitude=&quot;#####&quot; longitude=&quot;$$$$$&quot;/&gt;
        '''&lt;turningRadius&gt;200&lt;/turningRadius&gt;
        '''&lt;tidalLevel&gt;0&lt;/tidalLevel&gt;
        '''&lt;legType&gt;%%%%%&lt;/legType&gt;
        '''&lt;xte merge=&quot;false&quot;&gt;
        '''&lt;both-sided&gt;100&lt;/both-sided&gt;
        '''&lt;/xte&gt;
        '''&lt;antiGroundingStatus&gt;notChecked&lt;/antiGroundingStatus&gt;
        '''&lt;weatherOptimizable&gt;false&lt;/weatherOptimizable&gt;
        '''&lt;timeZone&gt;0&lt;/timeZone&gt;
        '''&lt;/waypoint&gt;.
        '''</summary>
        Public Shared ReadOnly Property String2() As String
            Get
                Return ResourceManager.GetString("String2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/waypoints&gt;
        '''&lt;/route&gt;.
        '''</summary>
        Public Shared ReadOnly Property String3() As String
            Get
                Return ResourceManager.GetString("String3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; standalone=&apos;yes&apos;?&gt;
        '''&lt;Voyage voyageId=&quot;?????&quot;&gt;
        ''' &lt;TrackInfo voyageId=&quot;&quot; rpm=&quot;495.00&quot; GM=&quot;3.00&quot; navFrom=&quot;1&quot; charterPartySpeed=&quot;&quot; ncrFuelRate=&quot;17.00&quot; beam=&quot;21.00&quot; length=&quot;138.00&quot; powerRatio=&quot;1.00&quot; shipName=&quot;SCS&quot; rollperiod=&quot;9.28&quot; ncrPower=&quot;1000.00&quot; callSign=&quot;SCS1&quot; trackCode=&quot;&quot; slip=&quot;10.00&quot; calmSeaSpeed=&quot;12.70&quot; ncrSpeed=&quot;12.70&quot;&gt;.
        '''</summary>
        Public Shared ReadOnly Property String4() As String
            Get
                Return ResourceManager.GetString("String4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Position Type=&quot;BR&quot; Lon=&quot;#####&quot; Position=&quot;@@@@@&quot; Name=&quot;@@@@@&quot; id=&quot;&quot; TimeFix=&quot;1&quot; ControlType=&quot;SC&quot; ControlValue=&quot;0&quot; Navigation=&quot;RL&quot; Lat=&quot;^^^^^&quot;/&gt;.
        '''</summary>
        Public Shared ReadOnly Property String5() As String
            Get
                Return ResourceManager.GetString("String5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Position Type=&quot;WP&quot; Lon=&quot;#####&quot; id=&quot;&quot; ControlType=&quot;SC&quot; ControlValue=&quot;0&quot; Navigation=&quot;RL&quot; Lat=&quot;^^^^^&quot;/&gt;.
        '''</summary>
        Public Shared ReadOnly Property String6() As String
            Get
                Return ResourceManager.GetString("String6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Position Type=&quot;ER&quot; Lon=&quot;#####&quot; Position=&quot;@@@@@&quot; Name=&quot;@@@@@&quot; id=&quot;&quot; ControlType=&quot;SC&quot; ControlValue=&quot;0&quot; Navigation=&quot;RL&quot; Lat=&quot;^^^^^&quot;/&gt;.
        '''</summary>
        Public Shared ReadOnly Property String7() As String
            Get
                Return ResourceManager.GetString("String7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;/TrackInfo&gt;
        '''&lt;/Voyage&gt;.
        '''</summary>
        Public Shared ReadOnly Property String8() As String
            Get
                Return ResourceManager.GetString("String8", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
